# ES
#spring.data.elasticsearch.repositories.enabled = true
#spring.data.elasticsearch.cluster-nodes = 127.0.0.1:9200
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.client.reactive.endpoints=es-cn-0pp1jyb600014xqtz.public.elasticsearch.aliyuncs.com:9200
spring.data.elasticsearch.client.reactive.username=elastic
spring.data.elasticsearch.client.reactive.password=Hfgj2020