#sharding-jdbc 配置
sharding.jdbc.bootstrap.enabled = true
sharding.jdbc.bootstrap.master.names = ds$->{0..1},base
sharding.jdbc.bootstrap.slave.names = ds$->{0..1}slave$->{0},baseslave$->{0..1}
sharding.jdbc.bootstrap.slave.key = slave
#未配置分片规则的表将通过默认数据源定位
sharding.jdbc.config.sharding.default-data-source-name = base
#打印sql
sharding.jdbc.config.sharding.props.sql.show = true
# 分库分表
sharding.jdbc.datasource.base.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.baseslave0.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.baseslave1.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds0slave0.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo0?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds1slave0.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo1?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true

sharding.jdbc.datasource.ds0.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo0?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true
sharding.jdbc.datasource.ds1.url = jdbc:mysql://rm-bp10l2jfsa52b00mabo.mysql.rds.aliyuncs.com:3306/demo1?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&useSSL=false&allowMultiQueries=true

sharding.jdbc.config.sharding.tables.tb_user.actual-data-nodes = ds$->{0..1}.tb_user_$->{0..2}
sharding.jdbc.config.sharding.tables.tb_user.database-strategy.standard.sharding-column = age
sharding.jdbc.config.sharding.tables.tb_user.database-strategy.standard.precise-algorithm-class-name = com.yizhitong.mall.repository.support.algorithm.base.DataBaseShardingAlgorithmForInteger
sharding.jdbc.config.sharding.tables.tb_user.table-strategy.standard.sharding-column = age
sharding.jdbc.config.sharding.tables.tb_user.table-strategy.standard.precise-algorithm-class-name = com.yizhitong.mall.repository.support.algorithm.base.TableShardingAlgorithmForInteger


