<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>mushroom</artifactId>
    <groupId>com.mairo</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>sharding</artifactId>

  <properties>
    <shardingsphere.version>4.0.0</shardingsphere.version>
  </properties>

  <dependencies>
    <!-- for spring boot -->
    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-jdbc-spring-boot-starter</artifactId>
      <version>${shardingsphere.version}</version>
    </dependency>
    <!-- for spring namespace -->
    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-jdbc-spring-namespace</artifactId>
      <version>${shardingsphere.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-jdbc-spring-boot-starter</artifactId>
      <version>${shardingsphere.version}</version>
    </dependency>

    <!-- 使用XA事务时，需要引入此模块 -->
    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-transaction-xa-core</artifactId>
      <version>${shardingsphere.version}</version>
    </dependency>

    <!-- 使用BASE事务时，需要引入此模块 -->
    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-transaction-base-seata-at</artifactId>
      <version>${shardingsphere.version}</version>
    </dependency
  </dependencies>
  >
</project>